#!/bin/bash

echo "🚀 Setting up Vercel Environment Variables"
echo ""
echo "Your Supabase credentials:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "NEXT_PUBLIC_SUPABASE_URL:"
echo "https://yicnbgdulgasifqelwrj.supabase.co"
echo ""
echo "NEXT_PUBLIC_SUPABASE_ANON_KEY:"
echo "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlpY25iZ2R1bGdhc2lmcWVsd3JqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIzNDg2MzMsImV4cCI6MjA3NzkyNDYzM30.-3w5D0Ljza-qTNXZvaRs5BDqyfsoiTT2Cqboj7aC-MM"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 Next Steps:"
echo ""
echo "1. Get DATABASE_URL from Supabase:"
echo "   → Go to: https://supabase.com/dashboard/project/yicnbgdulgasifqelwrj/settings/database"
echo "   → Copy 'Connection pooling' > 'Transaction Mode' string"
echo ""
echo "2. Add all 3 variables to Vercel:"
echo "   → Dashboard: https://vercel.com/byessilyurts-projects/yurtdisi-goc-rehberi/settings/environment-variables"
echo "   → Or run: vercel env add [VARIABLE_NAME]"
echo ""
echo "3. Redeploy:"
echo "   → Run: vercel --prod"
echo ""
echo "4. Initialize database:"
echo "   → Run: npx prisma db push"
echo ""
echo "✨ Your app will be live at: https://yurtdisi-goc-rehberi.vercel.app"
echo ""
